In [48]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import pandas as pd
digits=load_digits()

In [49]:
#Creating DataFrame
print(dir(digits))
df=pd.DataFrame(digits['data'])
df['target']=digits['target']
x=df.drop(df.target,axis=1)
y=df.target

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']


In [50]:
#Train_Test_Split_Way
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [51]:
# Model For Logisitic Regression
lor=LogisticRegression(max_iter=10000,class_weight='balanced')
lor.fit(x_train,y_train)
lor.score(x_test,y_test)

0.9861111111111112

In [52]:
# Model for Support Vectot Machine
SVM=SVC(kernel='linear',gamma=5)
SVM.fit(x_train,y_train)
SVM.score(x_test,y_test)

0.9888888888888889

In [53]:
#MOdel for Random Forest Classifier
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)
rfc.score(x_test,y_test)

0.9972222222222222

In [54]:
# K-Fold & Stratified Kfold Way
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

kf=KFold(n_splits=3)
skf=StratifiedKFold(n_splits=3)
skf

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [73]:
from sklearn.model_selection import cross_val_score
#res1=cross_val_score(RandomForestClassifier(),digits.data,digits.target)
res1=cross_val_score(RandomForestClassifier(n_estimators=100),x,y)
res1

array([0.99722222, 0.97777778, 0.99442897, 0.99442897, 0.97771588])

In [74]:
from sklearn.model_selection import cross_val_score
res2=cross_val_score(SVC(kernel='linear',gamma=5),x,y)
res2

array([0.97777778, 0.95      , 0.97493036, 0.97493036, 0.95264624])

In [77]:
from sklearn.model_selection import cross_val_score
res3=cross_val_score(LogisticRegression(max_iter=10000,class_weight='balanced'),x,y,cv=9)
res3

array([0.965     , 0.995     , 0.94      , 0.955     , 0.99      ,
       0.995     , 0.95477387, 0.92462312, 0.95477387])