In [1]:
import numpy as np
array1=np.array([[1,25,1,0,5],[2,3,4,4,5]])
print(array1)
print(type(array1))
array1.shape
array1.dtype

[[ 1 25  1  0  5]
 [ 2  3  4  4  5]]
<class 'numpy.ndarray'>


dtype('int32')

In [2]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.empty((5,4))

array([[9.43046721e-312, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000],
       [7.56587583e-307, 5.30276956e+180, 6.74640243e-067,
        6.98206173e-076],
       [3.45932221e-086, 3.35658848e-143, 6.01433264e+175,
        6.93885958e+218],
       [5.56218858e+180, 3.94356143e+180, 4.69611815e-033,
        6.59365763e-042],
       [5.97979209e+174, 3.69567312e-033, 5.82884001e-144,
        1.50008929e+248]])

In [5]:
import numpy as np
arr1=np.array([[7,8,61],
               [41,87,70]])

In [6]:
# axis 0= column #axis 1= row
print(arr1.sum(axis=1))
print(arr1.sum(axis=0))

[ 76 198]
[ 48  95 131]


In [7]:
len(dir(np))

620

In [8]:
arr2=np.array([[71,18,71],
               [51,17,50]])
arr1.dot(arr2.transpose())

array([[4972, 3543],
       [9447, 7070]])

In [9]:
arr3=arr2.transpose()
print(arr2)
print(arr3)

[[71 18 71]
 [51 17 50]]
[[71 51]
 [18 17]
 [71 50]]


In [10]:
arr2.dot(arr3)

array([[10406,  7477],
       [ 7477,  5390]])

In [11]:
import numpy as np
b=np.arange(7)
print(b)

[0 1 2 3 4 5 6]


In [14]:
c=np.array([5,8,6,2,44,74,52,74,74])
np.size(c)
#c=c.reshape(5,2)
d=np.argsort(c)
print(d)
for i in range(0,len(d)):
    if i==max(d):
        print(f"Maximum Value : {d[i]}")
    if i==min(d):
        print(f"Minimum Value : {d[i]}")

[3 0 2 1 4 6 5 7 8]
Minimum Value : 3
Maximum Value : 8


In [4]:
import numpy as np
array1=np.array([[1,25,1,0,5],[2,3,4,4,5]])
print(array1)
print(type(array1))
array1.shape
array1.dtype
np.zeros((5,5))
np.ones((4,4))
np.empty((5,4))
arr1=np.array([[7,8,61],
               [41,87,70]])	
# axis 0= column  #axis 1= row
print(arr1.sum(axis=1))
print(arr1.sum(axis=0))
len(dir(np))
arr2=np.array([[71,18,71],
               [51,17,50]])
arr1.dot(arr2.transpose())
arr3=arr2.transpose()
print(arr2)
print(arr3)
print(np.arange(7))
c=np.array([5,8,6,2,44,74,52,74,74])
np.size(c)
print(np.argsort(c))


[[ 1 25  1  0  5]
 [ 2  3  4  4  5]]
<class 'numpy.ndarray'>
[ 76 198]
[ 48  95 131]
[[71 18 71]
 [51 17 50]]
[[71 51]
 [18 17]
 [71 50]]
[0 1 2 3 4 5 6]
[3 0 2 1 4 6 5 7 8]
